
LIGHT_GRAY = '#F5F5F5'
LABEL_COLOR = '#25265E'
WHITE_COLOR = '#FFFFFF'
OFF_WHITE = '#F8FAFF'
LIGHT_BLUE = '#CCEDFF'

SMALL_FONT_STYLE = ('Arial', 16)
LARGE_FONT_STYLE = ('Arial', 40)
DIGIT_FONT_STYLE = ('Arial', 24, 'bold')
DEFAULT_FONT_STYLE = ('Arial', 20)
